import 'package:flutter/material.dart';
import 'package:get/get.dart';


class Language extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {

    // English
    'en Us': {
      'Bienvenue Sur': 'Welcome To',
      'Adopte': 'Adopte',
      'Candidat': 'Employee',
      'Inscrivez-vous gratuitement ou connectez-vous': 'Register for free or log in',
      'Continuer avec un email': 'Continue with an email',
      'Votre Email': 'Your Email',
      'Mot de passe': 'Password',
      'Mot de passe oublié': 'Forgot Password',
      'Nom': 'Name',
      "s'inscrire" : "Sign up",
      'Confirmer Le Mot De Passe': 'Confirm Password',
      'Connexion'  : 'Login',
      'ou': 'or',
      'De quel profil êtes-vous ?.\nÊtes-vous un :': 'Which profile are you ?\nAre you an :',
      'Recruteur': 'Employer',
      'Erreur': 'Error',
      'Veuillez sélectionner un profil': 'Please select a profile',
      'Continuer': 'Continue',
      'Créer Un Compte': 'Create An Account',
      'Prénom': 'First Name',
      'Nom': 'Last Name',
      'Numéro De Téléphone': 'Phone Number',
      'Ville': 'City',
      'Addresse Postale': 'Postal Address',
      "Communication": "Communication",
      "Travail d'équipe": "Teamwork",
      "Résolution de problèmes": "Problem Solving",
      "Gestion du temps": "Time Management",
      "Adaptabilité" : "Adaptability",
      "Esprit critique" : "Critical Thinking",
      "Créativité" : "Creativity",
      "Leadership" : "Leadership",
      'Choisissez vos compétences': 'Choose your skills',
      'Ma Recherche': 'My Search',
      'Développeur Full Stack': 'Full Stack Developer',
      'Ingénieur DevOps': 'DevOps Engineer',
      'Designer UI/UX' : 'UI/UX Designer',
      'Data Scientist' : 'Data Scientist',
      'Métier recherché' : 'Job sought',
      'Localité recherchée' : 'Location sought',
      'Type(s) de contrat' : 'Type(s) of contract',
      'CDI' : 'Permanent',
      'CDD' : 'Fixed-term',
      'Stage' : 'Internship',
      'Alternance' : 'Apprenticeship',
      'Intérim' : 'Temporary',
      'Indépendant/ Freelance' : 'Freelance',
      'Valider' : 'Validate',
      'Ma Situation' : 'My Situation',
      'Métier(s) recherché(s) (3 choix max)' : 'Job(s) sought (3 max)',
      'Développeur' : 'Developer',
      'Ingénieur' : 'Engineer',
      'Designer' : 'Designer',
      'Analyste' : 'Analyst',
      'Métiers sélectionnés:' : 'Selected jobs:',
      'Situation actuelle' : 'Current situation',
      'En poste' : 'Employed',
      'Sans emploi' : 'Unemployed',
      'Disponibilité' : 'Availability',
      'Immédiate' : 'Immediate',
      'À convenir' : 'To be agreed',
      "Niveau d'expérience" : "Experience level",
      'Junior' : 'Junior',
      'Intermédiaire' : 'Intermediate',
      'Senior' : 'Senior',
      'Niveau de qualification' : 'Qualification level',
      'Bac' : 'High School',
      'Bac+2' : 'Associate Degree',
      'Bac+3' : 'Bachelor Degree',
      'Bac+5' : 'Master Degree',
      'Enregistrer' : 'Save',
      'Vous avez fini toutes les cartes': 'You have finished all the cards',
      'Industrie': 'Industry',
      'Address Email De L\'entreprise': 'Company Email Address',
      'Nom De L\'entreprise': 'Company Name',
      'Taille De L\'entreprise': 'Company Size',
      'Valider': 'Validate',
      'Dans quel secteur êtes-vous ?': 'In which sector are you ?',
      'Compétences sélectionnées': 'Selected skills',
      'Aucune sélectionnée' : 'None selected',
      'Primaire' : 'Primary',
      'Secondaire' : 'Secondary',
      'Tertiaire' : 'Tertiary',
      'Quaternaire' : 'Quaternary',
      'Quinaire' : 'Quinary',
      'Dans quel secteur êtes-vous ?': 'In which sector are you ?',
      'Des industries telles que l\'agriculture, la pêche, la foresterie et l\'exploitation minière.' : 'Industries such as agriculture, fishing, forestry and mining.',
      'Industries telles que la fabrication, la construction et la production industrielle.' : 'Industries such as manufacturing, construction and industrial production.',
      'Des secteurs tels que la vente au détail, les transports, les services financiers, l’éducation, la santé et l’hôtellerie.' : 'Sectors such as retail, transportation, financial services, education, health and hospitality.',
      'Industries telles que le développement, les technologies de l’information, le conseil et d’autres services intellectuels.' : 'Industries such as development, information technology, consulting and other intellectual services.',
      'Ce secteur est sur les rôles de gestion et de prise de décision de haut niveau essentiels pour l’économie mondiale.' : 'This sector is about high-level management and decision-making roles essential to the global economy.',
      'Secteur(s) sélectionné(s)' : 'Selected sector(s)',
      'Aucun secteur sélectionné' : 'No sector selected',
      'Paramètres' : 'Settings',
      "Gestion des abonnements": "Subscription management",
      "Gestion des notifications" : "Notification management",
      "Gestion des abonnements emails" : "Email subscription management",
      "Sécurité et aides" : "Security and help",
      "Modification mot de passe" : "Change password",
      "Conditions générales d'utilisation" : "Terms of use",
      "Gestion des cookies" : "Cookie",
      "Politique de confidentialité" : "Privacy policy",
      "Signalr un problème" : "Report a problem",
      "Autres" : "Others",
      "Donner mon avis sur l'application" : "Give my opinion on the application",
      "L'application est à jour" : "The application is up to date",
      "Déconnexion" : "Logout",
      "Supprimer mon compte" : "Delete my account",
      'Employé polyvalent' : 'Versatile employee',
      '• Expérience préalable dans un environnement industriel\n• Capacité à travailler en équipe\n• Bonne condition physique'
          : '• Previous experience in an industrial environment\n• Ability to work in a team\n• Good physical condition',
      'Nous recherchons un employé polyvalent pour travailler dans une usine. Les responsabilités incluent l\'opération de machines, la maintenance de l\'équipement et l\'assistance aux autres employés selon les besoins.' : 'We are looking for a versatile employee to work in a factory. Responsibilities include operating machines, equipment maintenance and assisting other employees as needed.',

  },

    // French
      'fr FR': {
      'Bienvenue Sur': 'Bienvenue Sur',
      'Adopte': 'Adopte',
      'Candidat': 'Candidat',
      'Inscrivez-vous gratuitement ou connectez-vous': 'Inscrivez-vous gratuitement ou connectez-vous',
      'Continuer avec un email': 'Continuer avec un email',
      'Votre Email': 'Votre Email',
      'Mot de passe': 'Mot de passe',
      'Mot de passe oublié': 'Mot de passe oublié',
      'Nom': 'Nom',
      "s'inscrire" : "s'inscrire",
      'Confirmer Le Mot De Passe': 'Confirmer le mot de passe',
      'Connexion'  : 'Connexion',
      'ou': 'ou',
      'De quel profil êtes-vous ?.\nÊtes-vous un :': 'De quel profil êtes-vous ?.\nÊtes-vous un :',
      'Recruteur': 'Recruteur',
      'Erreur': 'Erreur',
      'Veuillez sélectionner un profil': 'Veuillez sélectionner un profil',
      'Continuer': 'Continuer',
      'Créer Un Compte': 'Créer Un Compte',
      'Prénom': 'Prénom',
      'Nom': 'Nom',
      'Numéro de téléphone': 'Numéro de téléphone',
      'Ville': 'Ville',
      'Addresse Postale': 'Addresse Postale',
      "Communication": "Communication",
      "Travail d'équipe": "Travail d'équipe",
      "Résolution de problèmes": "Résolution de problèmes",
      "Gestion du temps": "Gestion du temps",
      "Adaptabilité" : "Adaptabilité",
      "Esprit critique" : "Esprit critique",
      "Créativité" : "Créativité",
      "Leadership" : "Leadership",
      'Choisissez vos compétences': 'Choisissez vos compétences',
      'Ma Recherche': 'Ma Recherche',
      'Développeur Full Stack': 'Développeur Full Stack',
      'Ingénieur DevOps': 'Ingénieur DevOps',
      'Designer UI/UX' : 'Designer UI/UX',
      'Data Scientist' : 'Data Scientist',
      'Métier recherché' : 'Métier recherché',
      'Localité recherchée' : 'Localité recherchée',
      'Type(s) de contrat' : 'Type(s) de contrat',
      'CDI' : 'CDI',
      'CDD' : 'CDD',
      'Stage' : 'Stage',
      'Alternance' : 'Alternance',
      'Intérim' : 'Intérim',
      'Indépendant/ Freelance' : 'Indépendant/ Freelance',
      'Valider' : 'Valider',
      'Ma Situation' : 'Ma Situation',
      'Métier(s) recherché(s) (3 choix max)' : 'Métier(s) recherché(s) (3 choix max)',
      'Développeur' : 'Développeur',
      'Ingénieur' : 'Ingénieur',
      'Designer' : 'Designer',
      'Analyste' : 'Analyste',
      'Métiers sélectionnés:' : 'Métiers sélectionnés:',
      'Situation actuelle' : 'Situation actuelle',
      'En poste' : 'En poste',
      'Sans emploi' : 'Sans emploi',
      'Disponibilité' : 'Disponibilité',
      'Immédiate' : 'Immédiate',
      'À convenir' : 'À convenir',
      "Niveau d'expérience" : "Niveau d'expérience",
      'Junior' : 'Junior',
      'Intermédiaire' : 'Intermédiaire',
      'Senior' : 'Senior',
      'Niveau de qualification' : 'Niveau de qualification',
      'Bac' : 'Bac',
      'Bac+2' : 'Bac+2',
      'Bac+3' : 'Bac+3',
      'Bac+5' : 'Bac+5',
      'Enregistrer' : 'Enregistrer',
      'Vous avez fini toutes les cartes': 'Vous avez fini toutes les cartes',
      'Industrie': 'Industrie',
      'Address Email De L\'entreprise': 'Address Email De L\'entreprise',
      'Nom De L\'entreprise': 'Nom De L\'entreprise',
      'Taille De L\'entreprise': 'Taille De L\'entreprise',
      'Valider': 'Valider',
      'Dans quel secteur êtes-vous ?': 'Dans quel secteur êtes-vous ?',
      'Compétences sélectionnées': 'Compétences sélectionnées',
      'Aucune sélectionnée' : 'Aucune sélectionnée',
      'Primaire' : 'Primaire',
      'Secondaire' : 'Secondaire',
      'Tertiaire' : 'Tertiaire',
      'Quaternaire' : 'Quaternaire',
      'Quinaire' : 'Quinaire',
      'Dans quel secteur êtes-vous ?': 'Dans quel secteur êtes-vous ?',
      'Des industries telles que l\'agriculture, la pêche, la foresterie et l\'exploitation minière.' : 'Des industries telles que l\'agriculture, la pêche, la foresterie et l\'exploitation minière.',
      'Industries telles que la fabrication, la construction et la production industrielle.' : 'Industries telles que la fabrication, la construction et la production industrielle.',
      'Des secteurs tels que la vente au détail, les transports, les services financiers, l’éducation, la santé et l’hôtellerie.' : 'Des secteurs tels que la vente au détail, les transports, les services financiers, l’éducation, la santé et l’hôtellerie.',
      'Industries telles que le développement, les technologies de l’information, le conseil et d’autres services intellectuels.' : 'Industries telles que le développement, les technologies de l’information, le conseil et d’autres services intellectuels.',
      'Ce secteur est sur les rôles de gestion et de prise de décision de haut niveau essentiels pour l’économie mondiale.' : 'Ce secteur est sur les rôles de gestion et de prise de décision de haut niveau essentiels pour l’économie mondiale.',
      'Secteur(s) sélectionné(s)' : 'Secteur(s) sélectionné(s)',
      'Aucun secteur sélectionné' : 'Aucun secteur sélectionné',
      'Paramètres' : 'Paramètres',
      "Gestion des abonnements": "Gestion des abonnements",
      "Gestion des notifications" : "Gestion des notifications",
        "Gestion des abonnements emails" : "Gestion des abonnements emails",
        "Sécurité et aides" : "Sécurité et aides",
        "Modification mot de passe" : "Modification mot de passe",
        "Conditions générales d'utilisation" : "Conditions générales d'utilisation",
        "Gestion des cookies" : "Gestion des cookies",
        "Politique de confidentialité" : "Politique de confidentialité",
        "Signalr un problème" : "Signalr un problème",
        "Autres" : "Autres",
        "Donner mon avis sur l'application" : "Donner mon avis sur l'application",
        "L'application est à jour" : "L'application est à jour",
        "Déconnexion" : "Déconnexion",
        "Supprimer mon compte" : "Supprimer mon compte",
        'Employé polyvalent' : 'Employé polyvalent',
        '• Expérience préalable dans un environnement industriel\n• Capacité à travailler en équipe\n• Bonne condition physique'
            : '• Expérience préalable dans un environnement industriel\n• Capacité à travailler en équipe\n• Bonne condition physique',
        'Nous recherchons un employé polyvalent pour travailler dans une usine. Les responsabilités incluent l\'opération de machines, la maintenance de l\'équipement et l\'assistance aux autres employés selon les besoins.'
            : 'Nous recherchons un employé polyvalent pour travailler dans une usine. Les responsabilités incluent l\'opération de machines, la maintenance de l\'équipement et l\'assistance aux autres employés selon les besoins.',
      },
  };
}
